// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovzzvbfnxvmaagfzpcit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92enp2YmZueHZtYWFnZnpwY2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODU3OTMsImV4cCI6MjA2NTA2MTc5M30.CypQqc0Q06zt4XR60w_274r2SCQOzzvWE0wx8cNQq1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);